eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8701/eureka/
server:
  port: 8081
spring:
  application:
    name: service-zuul
#zuul:
#  routes:
#    api-ribbon:
#      path: /api-ribbon/**
#      serviceId: service-ribbon
#    api-eurka-client:
#      path: /api-eurka-client/**
#      serviceId: service-hi